#! /usr/bin/env sh
echo $password
if [ ! -f MoneroWallet ]; then
    /home/xmrwallet/monero-v0.12.0.0/monero-wallet-cli \
        --generate-new-wallet=MoneroWallet \
        --mnemonic-language=English \
        --password=$password \
        --daemon-host=$daemon_host \
        --daemon-port=$daemon_port | tee -a monero-wallet-generate.log
else
    /home/xmrwallet/monero-v0.12.0.0/monero-wallet-$iface \
        --wallet-file=MoneroWallet \
        --password=$password \
        --rpc-bind-ip 0.0.0.0 \
        --rpc-bind-port 18082 \
        --daemon-host=$daemon_host \
        --daemon-port=$daemon_port | tee -a monero-wallet-cli.log
fi
tail -f monero-wallet-cli.log
